apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-data
  labels:
    component: elasticsearch
    role: master
spec:
  ports:
  - name: transport
    port: 9300
  clusterIP: None
  selector:
    component: elasticsearch
    role: master
  