kind: PersistentVolume
apiVersion: v1
metadata:
  name: jenkins-pv-volume2
  labels:
    component: jenkins
    app: jenkins
    
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/jenkins"
