---
apiVersion: apps/v1beta1
kind: Deployment
metadata: 
  name: static-site-pod         # Name of the Deployment - unique name
spec:
  replica: 1
  template:
    metadata:
      labels:
        apps: static-site-pod   # This will search for pod with the label hello-world-1 (if already exist it will use otherwise will create from below docker image)
    spec:
      containers:
      - name: hello         # Name of the container (name doesn't matter)
        image: docker.io/seqvence/static-site:latest
        ports:
          - containerPort: 80 # Port exposed by conatiner


---
apiVersion: v1
kind: Service
metadata:
    name: static-site-svc             # Service name
    labels:
        app: static-site-svc-label    # Service label
spec:
    type: NodePort                    # Load Balancer, it can be your own load balancer
    ports:
    - port: 80                       # Exposed container port inside the pod
      nodePort: 30001                 # Exposed port to the outside world.
      protocol: TCP                   # this will be TCP always 
    selector:
      app: static-site-pod            # All Pods which matches this name will be part of this service, 
                                      # if number of pods increases the service will
                                      # Select all those node which matches the label and will perform the load balancing 