apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
    prometheus.io/scrape: "true"
    prometheus.io/scheme: "http"
    prometheus.io/port: "{{ .Values.ClientPort }}"
  name: {{ .Values.Name }}
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "{{ .Release.Name }}-{{ .Values.Component }}"
spec:
  ports:
  - port: {{ .Values.PeerPort }}
    name: etcd-server
  - port: {{ .Values.ClientPort }}
    name: etcd-client
  clusterIP: None
  selector:
    component: "{{ .Release.Name }}-{{ .Values.Component }}"
