apiVersion: v1
kind: ReplicationController
metadata:
  name: web
  labels:
    name: web
    app: demo
spec:
  replicas: 2
  template:
    metadata:
      name: web
      labels:
        name: web
        app: demo
    spec:
        containers:
          - name: redis
            image: redis
            ports:
              - containerPort: 6379
                name: redis
                protocol: TCP
          - name: python
            image: mjindal/multicontainerpod:6.0
            env:       
              - name: "REDIS_HOST"
                value: "localhost"
            ports:
              - containerPort: 5000
                name: http
                protocol: TCP   