apiVersion: v1
kind: Service
metadata:
  name: myflask-web
  labels:
    name: myflask
    app: myflask-demo
spec:
  selector:
    name: multicontainer-myflask
  type: NodePort
  ports:
   - port: 80
     name: http
     targetPort: 5000
     protocol: TCP