kind: PersistentVolume
apiVersion: v1
metadata:
  name: elasticsearch-pv-1
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/iesdgrid/mjindal/elasticsearch"
