kind: PersistentVolume
apiVersion: v1
metadata:
  name: prometheus-pv-volume1
  labels:
    component: prometheus
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/etc/prometheus"
