kind: PersistentVolume
apiVersion: v1
metadata:
  name: task-pv-nfs-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/ies/iesd_data12_nb/iesd_automation"
