# Default values for etcd.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value
common: 
  image:
    repository: ----
    tag: ----
    pullPolicy: IfNotPresent
    pullSecrets: ---
Name: lps-etcd
PeerPort: 2380
ClientPort: 2379
Component: "etcd"
Replicas: 1
Cpu: "100m"
Memory: "512Mi"
Storage: "1Gi"
## etcd data Persistent Volume Storage Class
## If defined, StorageClassName: <storageClass>
## If set to "-", StorageClassName: "", which disables dynamic provisioning
## If undefined (the default) or set to null, no storageClassName spec is
##   set, choosing the default provisioner.  (gp2 on AWS, standard on
##   GKE, AWS & OpenStack)
##
StorageClass: "portworx-high-io-priority-rf1"
