kind: PersistentVolume
apiVersion: v1
metadata:
  name: grafana-pv-volume1
  labels:
    component: grafana
    app: grafana-grafana
    
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp"
