apiVersion: v1
kind: ReplicationController
metadata:
  name: mysql
  labels:
    name: web
    app: demo
spec:
  replicas: 1
  template:
    metadata:
      name: mysql
      labels:
        name: mysql
        app: demo
    spec:
      containers:
        - name: mysql
          image: mysql:latest
          ports:
            - containerPort: 3306         
              protocol: TCP
          env: 
            - name: "MYSQL_ROOT_PASSWORD"
              value: "password"